version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule sync && git submodule update --init
      - restore_cache:
          key: v2-toolchain-checksum-{{ checksum "util/install-toolchain.sh" }}
      - run:
          name: Install toolchain
          command: ./util/install-toolchain.sh
      - save_cache:
          key: v2-toolchain-checksum-{{ checksum "util/install-toolchain.sh" }}
          paths:
            - "~/toolchains/"
      - run:
          name: Compile firmware
          command: echo $PREFIX && make -f release.Makefile -k all V=1
          environment:
            PREFIX: "~/toolchains/gcc-arm-embedded/bin/arm-none-eabi-"
      - store_artifacts:
          path: build/
